### PR TITLE
CORTX-29977-F-24F Log enhancement and update TODOs

### PR DESCRIPTION
**Pull request by Pradeep-B-Thangaraj**
Signed-off-by: Pradeep-B-Thangaraj <pradeep.b.thangaraj@seagate.com>

# Problem Statement
- CORTX-29977 - TA: Update the existing test script for Pod Failure handling

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by Pradeep-B-Thangaraj** [comment]
Pytest collect log

================================================================ short test summary info =================================================================
ERROR tests/csm/rest/test_capacity_usage.py
ERROR tests/csm/rest/test_csm_load.py
ERROR tests/csm/rest/test_csm_users.py
ERROR tests/csm/rest/test_iam_users.py
ERROR tests/csm/rest/test_s3_users.py
ERROR tests/csm/rest/test_system_stats.py
ERROR tests/security/test_cortx_port_scanner_kubectl_svc.py
ERROR tests/security/test_cortx_port_scanner_netstat.py
======================================================== 1810 tests collected, 8 errors in 5.56s =========================================================

Errors due to : CORTX-28785

**Comment by Pradeep-B-Thangaraj** [comment]
**Test set logs and terminal log**
[TEST-30220_TestFailureHandlingPodFailure_20220407020905.log](https://github.com/Seagate/cortx-test/files/8442125/TEST-30220_TestFailureHandlingPodFailure_20220407020905.log)
[TEST-30222_TestFailureHandlingPodFailure_20220407021153.log](https://github.com/Seagate/cortx-test/files/8442136/TEST-30222_TestFailureHandlingPodFailure_20220407021153.log)
[terminal.log](https://github.com/Seagate/cortx-test/files/8442145/terminal.log)
.

**Review by Jyoti-cs — APPROVED** [review]
Looks Good.

**Review by KASwami — APPROVED** [review]
Looks good to me

**Review by sonalk0209 — APPROVED** [review]
Approving for merge!!

**Pull request merged**
