### PR TITLE
Added fix for HA log handling

### PR DESCRIPTION
**Pull request by Pradeep-B-Thangaraj**
Signed-off-by: Pradeep-B-Thangaraj <pradeep.b.thangaraj@seagate.com>

# Problem Statement
- HA log handling

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by Pradeep-B-Thangaraj** [comment]
=========================================================== ERRORS ============================================================
___________________________________ ERROR collecting tests/csm/rest/test_capacity_usage.py ____________________________________
ImportError while importing test module '/root/public/cortx-test-1/tests/csm/rest/test_capacity_usage.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/csm/rest/test_capacity_usage.py:37: in <module>
    from libs.csm.csm_interface import csm_api_factory
libs/csm/csm_interface.py:30: in <module>
    from libs.csm.rest.csm_rest_stats import SystemStats
libs/csm/rest/csm_rest_stats.py:28: in <module>
    from prometheus_client.parser import text_string_to_metric_families
E   ModuleNotFoundError: No module named 'prometheus_client'
______________________________________ ERROR collecting tests/csm/rest/test_csm_load.py _______________________________________
ImportError while importing test module '/root/public/cortx-test-1/tests/csm/rest/test_csm_load.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/csm/rest/test_csm_load.py:39: in <module>
    from libs.csm.rest.csm_rest_stats import SystemStats
libs/csm/rest/csm_rest_stats.py:28: in <module>
    from prometheus_client.parser import text_string_to_metric_families
E   ModuleNotFoundError: No module named 'prometheus_client'
______________________________________ ERROR collecting tests/csm/rest/test_csm_users.py ______________________________________
ImportError while importing test module '/root/public/cortx-test-1/tests/csm/rest/test_csm_users.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/csm/rest/test_csm_users.py:48: in <module>
    from libs.csm.csm_interface import csm_api_factory
libs/csm/csm_interface.py:30: in <module>
    from libs.csm.rest.csm_rest_stats import SystemStats
libs/csm/rest/csm_rest_stats.py:28: in <module>
    from prometheus_client.parser import text_string_to_metric_families
E   ModuleNotFoundError: No module named 'prometheus_client'
______________________________________ ERROR collecting tests/csm/rest/test_iam_users.py ______________________________________
ImportError while importing test module '/root/public/cortx-test-1/tests/csm/rest/test_iam_users.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/csm/rest/test_iam_users.py:38: in <module>
    from libs.csm.csm_interface import csm_api_factory
libs/csm/csm_interface.py:30: in <module>
    from libs.csm.rest.csm_rest_stats import SystemStats
libs/csm/rest/csm_rest_stats.py:28: in <module>
    from prometheus_client.parser import text_string_to_metric_families
E   ModuleNotFoundError: No module named 'prometheus_client'
______________________________________ ERROR collecting tests/csm/rest/test_s3_users.py _______________________________________
ImportError while importing test module '/root/public/cortx-test-1/tests/csm/rest/test_s3_users.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/csm/rest/test_s3_users.py:38: in <module>
    from libs.csm.csm_interface import csm_api_factory
libs/csm/csm_interface.py:30: in <module>
    from libs.csm.rest.csm_rest_stats import SystemStats
libs/csm/rest/csm_rest_stats.py:28: in <module>
    from prometheus_client.parser import text_string_to_metric_families
E   ModuleNotFoundError: No module named 'prometheus_client'
____________________________________ ERROR collecting tests/csm/rest/test_system_stats.py _____________________________________
ImportError while importing test module '/root/public/cortx-test-1/tests/csm/rest/test_system_stats.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/csm/rest/test_system_stats.py:39: in <module>
    from libs.csm.rest.csm_rest_stats import SystemStats
libs/csm/rest/csm_rest_stats.py:28: in <module>
    from prometheus_client.parser import text_string_to_metric_families
E   ModuleNotFoundError: No module named 'prometheus_client'
___________________________ ERROR collecting tests/security/test_cortx_port_scanner_kubectl_svc.py ____________________________
ImportError while importing test module '/root/public/cortx-test-1/tests/security/test_cortx_port_scanner_kubectl_svc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/security/test_cortx_port_scanner_kubectl_svc.py:24: in <module>
    from kubernetes import client, config
E   ModuleNotFoundError: No module named 'kubernetes'
_____________________________ ERROR collecting tests/security/test_cortx_port_scanner_netstat.py ______________________________
ImportError while importing test module '/root/public/cortx-test-1/tests/security/test_cortx_port_scanner_netstat.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/security/test_cortx_port_scanner_netstat.py:22: in <module>
    from kubernetes import client, config
E   ModuleNotFoundError: No module named 'kubernetes'
=================================================== short test summary info ===================================================
ERROR tests/csm/rest/test_capacity_usage.py
ERROR tests/csm/rest/test_csm_load.py
ERROR tests/csm/rest/test_csm_users.py
ERROR tests/csm/rest/test_iam_users.py
ERROR tests/csm/rest/test_s3_users.py
ERROR tests/csm/rest/test_system_stats.py
ERROR tests/security/test_cortx_port_scanner_kubectl_svc.py
ERROR tests/security/test_cortx_port_scanner_netstat.py
=========================================== 1806 tests collected, 8 errors in 9.27s ===========================================

Errors due to : CORTX-28785

**Review by KASwami — APPROVED** [review]
Looks good.

**Review by sonalk0209 — APPROVED** [review]
approving for merge

**Comment by Pradeep-B-Thangaraj** [comment]
Closing due to check run stuck error.

**Pull request closed without merging**
