### PR TITLE
CORTX-29883-Cluster Start-F-8I

### PR DESCRIPTION
**Pull request by Pradeep-B-Thangaraj**
Signed-off-by: Pradeep-B-Thangaraj <pradeep.b.thangaraj@seagate.com>

# Problem Statement
- TA for Cluster Start

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [x] New/Affected tests are executed on Latest Build
-  [x] Attach test execution logs
-  [x] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by Pradeep-B-Thangaraj** [comment]
**Test execution logs**
[terminal.log](https://github.com/Seagate/cortx-test/files/8560608/terminal.log)
[TEST-30698_TestShutdownStartCluster_20220425011004.log](https://github.com/Seagate/cortx-test/files/8560609/TEST-30698_TestShutdownStartCluster_20220425011004.log)
[TEST-30700_TestShutdownStartCluster_20220425012436.log](https://github.com/Seagate/cortx-test/files/8560610/TEST-30700_TestShutdownStartCluster_20220425012436.log)
[TEST-30701_TestShutdownStartCluster_20220425010528.log](https://github.com/Seagate/cortx-test/files/8560611/TEST-30701_TestShutdownStartCluster_20220425010528.log)
[TEST-34982_TestShutdownStartCluster_20220425011457.log](https://github.com/Seagate/cortx-test/files/8560613/TEST-34982_TestShutdownStartCluster_20220425011457.log)

**Review by KASwami — APPROVED** [review]
Looks good to me

**Review by Jyoti-cs — APPROVED** [review]
Looks good.

**Comment by Pradeep-B-Thangaraj** [comment]
**Collection logs output**
Capture

**Review by sonalk0209 — APPROVED** [review]
approved for merge!!!!

**Pull request merged**
