### PR TITLE
Health check & test count

### PR DESCRIPTION
**Pull request by akshaym99**
Signed-off-by: akshaym99 <akshay.s.mankar@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by akshaym99** [comment]
@sonalk0209 please review
Jenkins run in Debug: https://eos-jenkins.mero.colo.seagate.com/job/QA-Sanity-Debug-Pipeline/101/ 
https://eos-jenkins.mero.colo.seagate.com/job/QA-Sanity-Debug-Pipeline/108/

**Comment by akshaym99** [comment]
Email template updates are uploaded at: https://jts.seagate.com/browse/CORTX-30417

**Review by sonalk0209 — APPROVED** [review]
LGTM

**Review by ketanarlulkar — APPROVED** [review]
Approved for merging

**Pull request merged**
